name: prop_commands
description: A set of utility classes for creating properties and commands
  in classes that extend ChangeNotifier.
version: 0.1.0
repository: https://github.com/bulsond/prop_commands

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
